---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.21.31

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[custom_apache::default]
    attributes:
